name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
    
    - name: Configure and Build
      run: |
        ./autogen.sh
        ./configure --host=x86_64-w64-mingw32
        make
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ptunnel-ng-windows
        path: src/ptunnel-ng.exe
